package com.example.czn.util.type;

public enum  WaitingType {
    START, START_DATE,
    CHOOSE_OPTION,
    END_DATE,
    COMMAND_EDITOR,
    UPDATE_BUTTON,
    UPDATE_TEXT,
    UPDATE_FILE,
    UPDATE_BUTTON_LINK,
    SET_FULL_NAME, SUGGESTION, COMPLAINT, CHOOSE_SURVEY, CHOOSE_OPTION_SURVEY, SET_NAME_RU, SET_NAME_KZ, SET_QUEST_RU,
    SET_QUEST_KZ, SET_LOCATION, SET_ANSWER_OF_QUEST_RU, SET_ANSWER_OF_QUEST_KZ, LEVEL_OF_EDUCATION, FULL_NAME_INSTITUTE, SPECIALTY, RECEIPT_DATE,
    EXPIRATION_DATE, NAME_OF_COMPANY, POSITION, INDUSTRY, DEVICE_DATE, DATE_OF_DISMISSAL, CAREER_OBJECTIVE,
    HOME_PHONE_NUMBER, SET_PHONE_NUMBER, E_MAIL, CHOOSE_SURVEY_FOR_EDIT, UPDATE_SURVEY, UPDATE_QUEST, QUEST_EDITION, SET_NEW_NAME,
    EDITION, SET_NEW_QUEST_TEXT, DELETE, GET_RANGE, SET_RANGE, DELETE_QUEST, SET_QUESTION, SET_EMAIL,SET_FULLNAME,SET_IIN,SET_FONE,
    CHOOSE_USER, SUBSCRIBE, SUBSCRIBE2,FOLLOW,UNFOLLOW,SET_DATE,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,TEN,BUTTON_EDITION_NAME,
    BUTTON_EDITION_MESSAGE,DELETE_FILE,LAST,ADD_FILE,INTERNAL_MENU,COURSES,SEMINARS,CONTESTS,ADDING,GET_INFO,SELECTING,SAVE,NAME_EDIT,DESCRIPTION_EDIT,SALARY_EDIT,
    TURN_OFF_ON,PRICE_EDIT,DURATION_EDIT

}
